### ISSUE TITLE
Create Endpoint to create a new ToDo

### ISSUE THREAD

**Issue by luka-lta** [luka-lta/task_wave_backend#28]
- [x] Create new ToDo
- [x] Required: Title
- [x] Optional: Description, Category, Deadline, Priority, Status, Pinned
- [x] Get Category by UserId and add them to ToDo
- [x] Calculate start and end of task
